export const appGenres = [
    {
        label:'All',
        value:'all'
    },
    {
        label:'Action',
        value:'action'
    },
    {
        label:'Horror',
        value:'horror'
    },
    {
        label:'Drama',
        value:'drama'
    },
    {
        label:'Comedy',
        value:'comedy'
    },
    {
        label:'Fantasy',
        value:'fantasy'
    }
]